name: CICD

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
      - 'alpha'
      - 'beta'
  pull_request:
    types: [opened, reopened, synchronize]
  merge_group:

jobs:
  call-workflow:
    permissions:
      id-token: write
      contents: write
      actions: write
      checks: write
      issues: write
      packages: write
      pull-requests: write
    uses: IvanJosipovic/templates/.github/workflows/csharp-publish-nuget.yaml@main